import React from "react";
import "../styles/global.css";
import BaseLayout from "@/layouts/baseLayout";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <BaseLayout>{children}</BaseLayout>
      </body>
    </html>
  );
}
// dark:bg-gradient-to-r from-gray-900 to-black
